[server]
headless = true
enableCORS = false
enableXsrfProtection = false
port = 8501

[browser]
gatherUsageStats = false
serverAddress = "localhost"

[theme]
base = "dark"
backgroundColor = "#010a08"
secondaryBackgroundColor = "#000d0d"
textColor = "#00e5cc"
font = "monospace"
